@extends('layouts.master')

 

@section('content')
 <script src="/js/jquery-1.12.4.min.js"></script>
<script src="/js/form-scripts.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $('#print_title').text('Reprinting History');
  });
</script>

<meta charset=utf-8 />
<div class="box box-primary">
  <div class="form-horizontal">
  <div id='print_content' class="print_content">
    <center>
<div class="box-body">
<br>   

    @foreach($printings as $print)
    @endforeach
      <h4 style="text-align:left;">
          
      </h4>
 <br>
     <h4 style="text-align: left !important"> Period Covered: @php echo date('M d, Y', strtotime($date_range_from)); @endphp - @php echo date('M d, Y', strtotime($date_range_to)); @endphp</h4>
<table  class="table table-bordered" style="margin:0; width:100%; border:1px solid black !important;">
  <thead style="text-align:left !important;">
  <tr style="border:1px solid black;">       
          <th style="border:1px solid black !important; text-align:center !important;">Copyright</th>
           <th style="border:1px solid black !important; text-align:center !important;">Reprinting Date</th>
          <th style="border:1px solid black !important; text-align:center !important;">Contractor/Donor</th>
          <th style="border:1px solid black !important; text-align:center !important;">Printing Cost</th>
          <th style="border:1px solid black !important; text-align:center !important;">Pcs</th>
          <th style="border:1px solid black !important; text-align:center !important;">Remarks</th>
</tr>
</thead>
<tbody>
      @foreach($printings as $printing)
      <tr>
      <td style="border:1px solid black !important; text-align: center !important;">@php 
        echo date('Y', strtotime($printing->created_at)); 
      @endphp
      </td>
      <td style="border:1px solid black !important; text-align: center !important;">@php echo date('M d, Y', strtotime($printing->iec_printing_date)); @endphp</td>
      <td style="border:1px solid black !important; text-align: left !important;">{{$printing->contractor_name}}</td>   
      <td style="border:1px solid black !important; text-align: center !important;">
                  @php
                  if($printing->iec_printing_cost == 'N/A')
                    echo 'N/A'; 
                  if($printing->iec_printing_cost != 'N/A')
                    echo number_format($printing->iec_printing_cost); 
                  @endphp
                </td>         
      <td style="border:1px solid black !important; text-align: center !important;">
              @php 
              echo number_format($printing->iec_printing_pcs);
              @endphp</td>
      <td style="border:1px solid black !important; text-align: center !important;">{{$printing->iec_printing_remarks}}</td>
   </tr>
    @endforeach
    <tr>
      <td style="border:1px solid black !important; text-align:center !important;" colspan="7">
      *** Nothing Follows ***
      </td>
    </tr>
</table>
 
  <br>
  <br> 
 <table style="width:100%; background-color: none !important;">
  <tr>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <br>
     <br>
    </td>
    <td style="width:20%; background-color: none !important; text-align:center !important;">
     <br>
     <br>
    </td>    
    <td style="width:30%; background-color: none !important; text-align:center !important;">
      <b>Date Generated:</b>
      <br>
     @php
     date_default_timezone_set("Asia/Manila");
     echo date("F d, Y");  @endphp
     <br>
     <br>
    </td>
  </tr>
</table>
 <table style="width:100%; background-color: none !important;">
  <tr>
    <td>
      <br>
     <br>
    </td>
    <td>
      <br>
     <br>
    </td>
  </tr>
  <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
  <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
  <tr>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <b>Report Generated By:</b> 
     <br>
     <br>
     <br>
     <br>
     {{Auth::user()->name}}
     <br>
     {{Auth::user()->user_position}} 
    </td>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <b>Noted By:</b> 
     <br>
     <br>
     <br>
     <br>
     {{$usigns}}
     <br>
     {{$uposition}}
    </td>
  </tr>
</table>
        </div>
  </div> 
   
</center>
</div>
 <button id="btnPrintingLogsPreview" style="visibility:hidden;">Print</button>
@endsection
 