@extends('layouts.master')

 

@section('content')
 <script src="/js/jquery-1.12.4.min.js"></script>
<script src="/js/form-scripts.js"></script>

<meta charset=utf-8 />
<div class="box box-primary">
  <div class="form-horizontal">
  <div id='print_content' class="print_content">
    <center>
<div class="box-body">
<br>   
 
    @foreach($transactions as $transaction)
    @endforeach
     <h4 style="text-align: left !important"> Period Covered: @php echo date('M d, Y', strtotime($date_range_from)); @endphp - @php echo date('M d, Y', strtotime($date_range_to)); @endphp</h4>
<table class="table" style="margin:0; width:100%; border:1px solid black !important;">
  <thead style="text-align:left !important;">
  <tr style="border:1px solid black;">
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important; font-size: 10px !important;"><b>No</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important; font-size: 10px !important;"><b>Trans. No.</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important;font-size: 10px !important;"><b>Name of Client</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important;font-size: 10px !important;"><b>Organization</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important;font-size: 10px !important;"><b>Requested Material</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important; width:10%;font-size: 10px !important;"><b>Pcs.</b></th>
    <th style="vertical-align: middle; border:1px solid black !important; text-align:center !important;font-size: 10px !important;"><b>Staff in Charge</b></th>
</tr>
</thead>
<tbody style="font-size: 10px !important;">
  @php $x = 0; @endphp

      @foreach($transactions as $transaction)   
    <tr>
      <td style="border:1px solid black !important; text-align:center !important;">
    @php
    $x = $x + 1;
    echo $x;
    @endphp
 
      </td>      
      <td style="border:1px solid black !important; text-align:center !important;">
            <center>
             {{$transaction->transNO}}  <br>
            </center>      
        </td>     
      <td style="border:1px solid black !important; text-align:center !important;">
        <center>
          {{$transaction->client_name}}  
        </center>
      </td>
      <td style="border:1px solid black !important; text-align:center !important;">
        <center>
          {{$transaction->organization_name}} 
        </center>
      </td> 
 
      <td style=" border:1px solid black !important; text-align:left !important;">
        {{$transaction->iec_title}} 
      </td>

      <td style="border:1px solid black !important; text-align:center !important;">
        @php 
        echo number_format($transaction->request_material_quantity); @endphp
      </td>

      <td style="border:1px solid black !important; text-align:center !important;">
        {{$transaction->name}}
      </td>
  @endforeach
    <tr>
      <td style="border:1px solid black !important; text-align:center !important;" colspan="8">
      *** Nothing Follows ***
      </td>
    </tr>
 </tbody>
</table>
  <br>
  <br> 
 <table style="width:100%; background-color: none !important;">
  <tr>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <br>
     <br>
    </td>
    <td style="width:20%; background-color: none !important; text-align:center !important;">
     <br>
     <br>
    </td>    
    <td style="width:30%; background-color: none !important; text-align:center !important;">
      <b>Date Generated:</b>
      <br>
     @php
     date_default_timezone_set("Asia/Manila");
     echo date("F d, Y");  @endphp
     <br>
     <br>
    </td>
  </tr>
</table>
 <table style="width:100%; background-color: none !important;">
  <tr>
    <td>
      <br>
     <br>
    </td>
    <td>
      <br>
     <br>
    </td>
  </tr>
  <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
  <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
  <tr>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <b>Report Generated By:</b> 
     <br>
     <br>
     <br>
     <br>
     {{Auth::user()->name}}
     <br>
     {{Auth::user()->user_position}}
    </td>
    <td style="width:50%; background-color: none !important; text-align:center !important;">
     <b>Noted By:</b> 
     <br>
     <br>
     <br>
     <br>
     {{$usigns}}
     <br>
     {{$uposition}}
    </td>
  </tr>
</table>
        </div>
  </div> 
   
  </div> <!-- /.box-body -->
</center>
</div>
 <button id="btnPrintPreview" style="visibility:hidden;">Print</button>
@endsection
 